### ISSUE TITLE
Very Novice--Help, please

### ISSUE THREAD

**Issue by blackfern** [fredbenenson/lunch-roulette#7]
I'm using Excel. Where do I put the commands? How do I run this?  Can anyone be so kind as to tell me step by step instructions? I have the files on my computer, I've changed the weights, teams and specialties to match my own csv file, but how do run the app?

**Comment by fredbenenson** [comment]
Hi @blackfern! Thanks for checking out Lunch Roulette. Unfortunately using the program requires a little more than Excel – you'll need experience with the command line and Ruby installed on your system. 

Here's more info on how to get started there: 

https://www.codecademy.com/articles/ruby-setup

This issues board is for actual bugs in the software so I'm going to close this comment for now.
